interval = 5 # default 5

[grpc]
server = true # default false
# type = "tcp"  # default unix
# path ="knotidx.sock"  # default XDG_RUNTIME_DIR/knotidx.sock
# host = "localhost" # default
# port = 5319   # default 5319

[store]
type = "badger" # default "badger"
# path = "store.knot"

[[indexer]]
type = "fs"
notify = true
paths = ["/tmp"]

# [[indexer]]
# type = "fs"
# notify = true
# paths = ["/home/shtirlic/projects", "/home/shtirlic/kernel"]

# [[indexer]]
# type = "fs"
# notify = true
# paths = ["/home/shtirlic/kde"]
